version: 2

build:
  commands:
    - echo "Building SAI RAG Chatbot with organized structure..."
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Build completed successfully"

run:
  command: python main.py

env:
  - key: PYTHON_VERSION
    value: 3.11.0
  - key: PYTHONPATH
    value: /opt/render/project/src
  - key: FLASK_ENV
    value: production
  - key: PORT
    value: 5000